### PR TITLE
Adds new link for WebSVF 3.0 and fix deployment automation for GitHub Pages

### PR DESCRIPTION
**Pull request by Re-Tails**
Added a new link for WebSVF 3.0 and fix deployment automation for GitHub Pages, legacy deployment steps are commented out now

### CODE REVIEW

**Comment by yuleisui** [comment]
There is a conflict must be resolved

**Comment by Re-Tails** [comment]
It should be resolved now sir

**Comment by yuleisui** [comment]
Are you using the latest version of SVF-example as your backend?

**Comment by yuleisui** [comment]
The websvf’s home page does not have the link to your webpage. It is not working

**Comment by Re-Tails** [comment]
> Are you using the latest version of SVF-example as your backend?
I was also using Ian's https://github.com/Ian36/CapstoneProject

> The websvf’s home page does not have the link to your webpage. It is not working
Can you check again now sir, it took a few mins

**Comment by yuleisui** [comment]
Can you use the lastest version of SVF-example?

**Comment by yuleisui** [comment]
The link looks ok to me

**Comment by Re-Tails** [comment]
> Can you use the lastest version of SVF-example?

I can try and implement that yeah

**Pull request merged**
